import {
  ColorPanels,
  Dithering,
  DotGrid,
  DotOrbit,
  FlutedGlass,
  GemSmoke,
  GodRays,
  GrainGradient,
  HalftoneCmyk,
  HalftoneDots,
  Heatmap,
  ImageDithering,
  LiquidMetal,
  MeshGradient,
  Metaballs,
  NeuroNoise,
  PaperTexture,
  PerlinNoise,
  PulsingBorder,
  SimplexNoise,
  SmokeRing,
  Spiral,
  StaticMeshGradient,
  StaticRadialGradient,
  Swirl,
  Voronoi,
  Warp,
  Water,
  Waves,
} from "@paper-design/shaders-react"

export const PAPER_SHADER_COMPONENTS_BY_ID: Record<string, typeof Dithering> = {
  "mesh-gradient": MeshGradient,
  "static-mesh-gradient": StaticMeshGradient,
  "grain-gradient": GrainGradient,
  warp: Warp,
  waves: Waves,
  "dot-orbit": DotOrbit,
  voronoi: Voronoi,
  "smoke-ring": SmokeRing,
  "neuro-noise": NeuroNoise,
  "dot-grid": DotGrid,
  "simplex-noise": SimplexNoise,
  metaballs: Metaballs,
  "perlin-noise": PerlinNoise,
  "god-rays": GodRays,
  spiral: Spiral,
  swirl: Swirl,
  dithering: Dithering,
  "pulsing-border": PulsingBorder,
  "color-panels": ColorPanels,
  "static-radial-gradient": StaticRadialGradient,
  "paper-texture": PaperTexture,
  water: Water,
  "fluted-glass": FlutedGlass,
  "image-dithering": ImageDithering,
  heatmap: Heatmap,
  "liquid-metal": LiquidMetal,
  "halftone-dots": HalftoneDots,
  "halftone-cmyk": HalftoneCmyk,
  "gem-smoke": GemSmoke,
}

export function getPaperShaderComponent(shaderId: string) {
  return PAPER_SHADER_COMPONENTS_BY_ID[shaderId] ?? Dithering
}
